### PR TITLE
Fix event targent type erasure

### LINKED ISSUE #1516: Autocompletion method clash with javafx 21 due to changed event signature
I was trying out the latest EA of javafx 21 in our project and stumbled across this issue:
```
'addEventHandler(EventType<E>, EventHandler<E>)' in 'org.controlsfx.control.textfield.AutoCompletionBinding' clashes with 'addEventHandler(EventType<E>, EventHandler<? super E>)' in 'javafx.event.EventTarget'; both methods have same erasure, yet neither overrides the other

'removeEventHandler(EventType<E>, EventHandler<E>)' in 'org.controlsfx.control.textfield.AutoCompletionBinding' clashes with 'removeEventHandler(EventType<E>, EventHandler<? super E>)' in 'javafx.event.EventTarget'; both methods have same erasure, yet neither overrides the other

```

### PR DESCRIPTION
**Pull request by Siedlerchr**
Bump to javafx 21
Fixes #1516

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Just signed the CLA

**Comment by credmond** [comment]
@jperedadnr: could you please merge this?

**Comment by johanvos** [comment]
It seems to me the JDK version needs to be fixed as well. What is the expected target release? JavaFX 21 required Java 17 or later, hence bytecode version 61. I see a failure in the GA: `class file has wrong version 61.0, should be 55.0` -> but 61 is the requirement for JavaFX 21.

**Comment by Siedlerchr** [comment]
Updated to jdk 17 in the workflows now as well

**Comment by johanvos** [comment]
This looks good, builds for me locally now.

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCell.java [hunk 1]
```diff
@@ -33,9 +33,7 @@
 import javafx.beans.property.ReadOnlyStringProperty;
 import javafx.beans.property.StringProperty;
 import javafx.collections.ObservableSet;
-import javafx.event.Event;
-import javafx.event.EventHandler;
-import javafx.event.EventType;
+import javafx.event.*;
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCell.java:36]: please revert wildcard import

File: gradle.properties [hunk 2]
```diff
@@ -1,4 +1,4 @@
 group = org.controlsfx
 controlsfx_version = 11.1.3-SNAPSHOT
 fxsampler_version = 1.0.12-SNAPSHOT
-javafx_version = 13
\ No newline at end of file
+javafx_version = 21
```
Comment (abhinayagarwal) [inline gradle.properties:4]: I would keep this as either 13 or move to the last LTS release i.e. 17

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/Grid.java [hunk 3]
```diff
@@ -241,7 +242,7 @@ public interface Grid {
      * @param eventHandler the handler to register
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/org/controlsfx/control/spreadsheet/Grid.java:242]: Please update the license year on each changed file

File: gradle.properties (hunk 2 above)
Comment (Siedlerchr) [reply gradle.properties:4]: Isn't 21 LTS as well?  At least that's what I read at https://gluonhq.com/products/javafx/
 The key issue was that it was a clash with javafx 21, therefore it makes sense to have this version here.

Comment (abhinayagarwal) [reply gradle.properties:4]: Yes, it is. However, ControlsFX is used across many applications and not everyone would move to latest version immediately.  The changes done is this PR makes sure that ControlsFX works with 21, but it also works with versions before 21. That's what I like about this PR :)

My personal preference is to keep the compatibility version as minimum as possible, so that more applications can use the library without having to move to the latest JavaFX version.

**Comment by Siedlerchr** [comment]
addressed your changes

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/Grid.java [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2013, 2018 ControlsFX
+ * Copyright (c) 2013, 2018, 2023 ControlsFX
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/org/controlsfx/control/spreadsheet/Grid.java:2]: This needs to be:

```
Copyright (c) 2013, 2023 ControlsFX
```

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/GridBase.java [hunk 5]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2013, 2018 ControlsFX
+ * Copyright (c) 2013, 2018, 2023 ControlsFX
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/org/controlsfx/control/spreadsheet/GridBase.java:2]: same here

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCell.java [hunk 6]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2014, 2018 ControlsFX
+ * Copyright (c) 2014, 2018, 2023 ControlsFX
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCell.java:2]: here as well

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCellBase.java [hunk 7]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2013, 2016, 2018 ControlsFX
+ * Copyright (c) 2013, 2016, 2018, 2023s ControlsFX
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCellBase.java:2]: same here. also mark the unwanted `s` at the end of 2023

File: controlsfx/src/main/java/org/controlsfx/control/textfield/AutoCompletionBinding.java [hunk 8]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2014, 2016, 2020 ControlsFX
+ * Copyright (c) 2014, 2016, 2020, 2023 ControlsFX
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/org/controlsfx/control/textfield/AutoCompletionBinding.java:2]: same here

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCellBase.java (hunk 7 above)
Comment (Siedlerchr) [reply controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCellBase.java]: I was just following the sequence...,but changed now

File: controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCell.java [hunk 9]
```diff
@@ -68,7 +68,26 @@ public interface SpreadsheetCell  {
...
+
+
+    /**
+     * Registers an event handler to this SpreadsheetCell.
+     *
+     * @param eventType the type of the events to receive by the handler
+     * @param eventHandler the handler to register
+     * @throws NullPointerException if the event type or handler is null
+     */
+     public  <E extends Event> void addEventHandler(EventType<E> eventType, EventHandler<? super E> eventHandler);
```
[the remark this answers is not in the document]
Comment (Siedlerchr) [reply controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetCell.java]: Moved them back down. Was not intended

**Review by abhinayagarwal — APPROVED** [review]
