### PR TITLE
Fix for Issue #1178

### LINKED ISSUE #1178: CustomTextFieldSkin should remove left/right pane if the property is set to null
Calling `setLeft(null)`/`setRight(null)` on a `CustomTextField` has no effect

### PR DESCRIPTION
**Pull request by Maxoudela**
This fixes #1178

### CODE REVIEW

File: controlsfx/src/main/java/impl/org/controlsfx/skin/CustomTextFieldSkin.java [hunk 1]
```diff
@@ -74,27 +74,35 @@ public CustomTextFieldSkin(final TextField control) {
     
     private void updateChildren() {
         Node newLeft = leftProperty().get();
+        //Remove leftPane in any case
```
Comment (abhinayagarwal) [inline controlsfx/src/main/java/impl/org/controlsfx/skin/CustomTextFieldSkin.java]: Please update the copyright year on the header.

File: controlsfx/src/test/java/org/controlsfx/control/textfield/CustomTextFieldTest.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+ * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+ * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+ */
+package org.controlsfx.control.textfield;
+
+import java.util.concurrent.TimeoutException;
+import javafx.scene.Scene;
+import javafx.scene.control.Label;
+import javafx.scene.layout.StackPane;
+import org.controlsfx.control.textfield.CustomTextField;
```
Comment (abhinayagarwal) [inline controlsfx/src/test/java/org/controlsfx/control/textfield/CustomTextFieldTest.java]: My IDE suggests this import shouldn't be required. Can you double check?

**Comment by Maxoudela** [comment]
Thanks for the review, I have updated the files.
